/* =====================================================================
   AfyaMind — Interactive Course Data
   "Understanding & Managing Anxiety and Stress"
   Full content parsed from the course document. Every module, lesson,
   reflection, exercise, audio script and resource is represented here.

   Block types used in lesson.body:
     { t:'p',    text }                 paragraph
     { t:'h',    text }                 sub-heading inside a lesson
     { t:'list', items:[...] }          bullet list
     { t:'ol',   items:[...] }          numbered list
     { t:'quote',label, text }          highlighted example / callout
     { t:'take', text }                 "Key takeaway" box
     { t:'interactive', widget:'...' }  renders an interactive tool
     { t:'fields', intro, rows:[...] }  worksheet with saved inputs
     { t:'questions', items:[...] }     reflection questions w/ saved answers
     { t:'resources', groups:[...] }    resource tables w/ links
   ===================================================================== */

const COURSE = {
  id: "anxiety-stress",
  title: "Understanding & Managing Anxiety and Stress",
  emoji: "🧠",
  audience: "General Adults",
  format: "Self-paced modules",
  duration: "45–60 mins total",
  summary:
    "Anxiety isn't the enemy — it's a signal. Across 6 modules and 18 lessons, you'll learn what anxiety is, recognise your patterns, build in-the-moment tools, reframe anxious thinking, create lasting resilience, and know when to seek more help.",
  modules: [
    {
      id: "m1",
      n: 1,
      title: "What's Actually Happening?",
      subtitle: "Psychoeducation",
      tagline:
        "Anxiety isn't your enemy — it's a signal. Let's learn what it's trying to tell you.",
      goal: "Help users understand anxiety isn't the enemy — it's a signal.",
      lessons: [
        {
          id: "l1-1",
          kind: "lesson",
          title: "What is Anxiety vs. Stress? (And Why Both Are Normal)",
          readTime: "4 min read",
          body: [
            { t: "p", text: "You've probably used the words anxiety and stress interchangeably. Most people do. But they're actually two different experiences — and understanding the difference is the first step to dealing with them more effectively." },
            { t: "p", text: "Stress is usually a response to something external. A deadline. A difficult conversation. A bill you weren't expecting. It tends to show up when demands feel bigger than your current resources. When the stressor goes away, the stress usually eases too." },
            { t: "p", text: "Anxiety is different. It's more internal. It can show up even when nothing is technically wrong — when life looks fine on the outside but something inside feels unsettled, tense, or on edge. Anxiety is often about anticipation — the what ifs, the worst-case scenarios, the feeling that something bad is coming even when you can't name it." },
            { t: "h", text: "Here's the most important thing to understand early:" },
            { t: "p", text: "Both anxiety and stress are completely normal human experiences. They are not signs of weakness. They are not signs that something is broken in you." },
            { t: "p", text: "Your brain developed these responses over thousands of years to keep you alive. When early humans faced real physical danger, anxiety and stress triggered a survival system — speeding up the heart, sharpening focus, flooding the body with energy to fight or flee. That system saved lives." },
            { t: "p", text: "The problem today is that your brain can't always tell the difference between a predator and a work email. It fires the same alarm for both." },
            { t: "p", text: "So when anxiety shows up, it's not betraying you. It's trying to protect you. Your job — and what this course will help you do — is learn how to work with that system instead of being controlled by it." },
            { t: "take", text: "Stress responds to external pressure. Anxiety lives in anticipation and internal experience. Both are normal. Both are manageable." },
          ],
        },
        {
          id: "l1-2",
          kind: "lesson",
          title: "What Happens in Your Body When Anxiety Kicks In",
          readTime: "4 min read",
          body: [
            { t: "p", text: "Have you ever noticed your heart racing before a big presentation? Your stomach tightening before a difficult conversation? Your mind going blank at the worst possible moment?" },
            { t: "p", text: "That's not a coincidence. That's your body doing exactly what it was designed to do." },
            { t: "p", text: "When your brain perceives a threat — real or imagined — it sends an immediate distress signal to a small, almond-shaped part of your brain called the amygdala. The amygdala doesn't think. It reacts. And its reaction triggers a cascade of physical changes throughout your body almost instantly." },
            { t: "h", text: "Here's what happens in those first few seconds:" },
            { t: "list", items: [
              "Your heart rate increases — pumping more blood to your muscles so you can move fast",
              "Your breathing quickens — bringing in more oxygen to fuel that movement",
              "Your muscles tighten — especially in your shoulders, chest, and jaw, preparing to act",
              "Your digestion slows down — your body redirects energy away from non-essential functions",
              "Your mind narrows its focus — scanning for the threat, which can feel like racing thoughts or inability to concentrate",
              "Your palms may sweat — an ancient mechanism to improve grip",
            ] },
            { t: "p", text: "This is your fight-or-flight response, and it is extraordinarily powerful. In a true emergency, it can save your life." },
            { t: "p", text: "The challenge is that it can also be triggered by things that aren't life-threatening at all — a social situation, a looming deadline, a memory, even a thought." },
            { t: "p", text: "And here's something that surprises many people: the physical sensations of anxiety can themselves become frightening, which causes more anxiety, which causes more physical symptoms. This is how panic can escalate quickly." },
            { t: "p", text: "Understanding this cycle is powerful because it gives you a place to intervene. You can't always control the trigger. But you can learn to calm your body's response — and that's exactly what we'll build toward in this course." },
            { t: "take", text: "Anxiety is a full-body experience driven by your brain's threat-detection system. The physical symptoms are real, not imagined — and they can be calmed." },
          ],
        },
        {
          id: "l1-3",
          kind: "lesson",
          title: "The Anxiety Cycle: How It Keeps Feeding Itself",
          readTime: "5 min read",
          body: [
            { t: "p", text: "One of the most frustrating things about anxiety is that the natural ways we try to escape it often make it worse in the long run. Understanding why this happens changes everything." },
            { t: "quote", label: "The cycle", text: "Trigger → Anxious thought → Physical response → Avoidance → Temporary relief → Anxiety grows stronger" },
            { t: "p", text: "Let's walk through a real example. Imagine you have a presentation at work coming up. The thought arrives: \"What if I mess up and everyone judges me?\" Your body tenses. Your heart rate picks up. The discomfort is real and unpleasant." },
            { t: "p", text: "So you do what feels logical — you avoid thinking about it. You distract yourself, delay your preparation, or mentally rehearse all the ways it could go wrong as a form of \"preparing.\" You get temporary relief from the sharpest edge of the anxiety." },
            { t: "p", text: "But here's what's happening underneath: your brain has just learned that this situation is dangerous enough to escape. Each time you avoid it, that message gets reinforced. The anxiety gets a little more permission to grow." },
            { t: "p", text: "This is called the anxiety cycle, and it's not a character flaw. It's a learning pattern. Your brain is doing what brains do — learning from experience. The problem is it's learning the wrong lesson." },
            { t: "h", text: "The three most common ways people feed the cycle without realizing it:" },
            { t: "list", items: [
              "Avoidance — staying away from situations, people, or thoughts that trigger anxiety. Feels like relief, functions like fuel.",
              "Reassurance seeking — constantly asking others \"do you think it'll be okay?\" The comfort lasts minutes. The need for it grows.",
              "Overthinking — mentally running through every possible scenario as a way of feeling in control. It feels productive. It rarely is.",
            ] },
            { t: "p", text: "None of these make you weak or broken. They make you human. But recognizing them in yourself is the first real act of change." },
            { t: "p", text: "The good news: because anxiety is a learned cycle, it can also be unlearned. Not overnight. But steadily, with the right tools — which is exactly what the rest of this course is about." },
            { t: "take", text: "Anxiety grows through avoidance and safety behaviors. Recognizing your personal cycle is the beginning of breaking it." },
          ],
        },
        {
          id: "l1-r",
          kind: "reflection",
          title: "Module 1 Reflection",
          readTime: "5 min",
          body: [
            { t: "p", text: "Take 5 minutes with these questions. There are no right or wrong answers — this is just for you." },
            { t: "questions", items: [
              "When you think about anxiety or stress in your own life, which feels more familiar to you — external pressure (stress) or internal unease (anxiety)?",
              "Looking at the physical symptoms from Lesson 1.2 — which ones do you recognize in yourself? Where does anxiety live in your body?",
              "Can you think of a situation where you avoided something because it made you anxious? What happened after?",
            ] },
            { t: "p", text: "You don't have to have this all figured out. Noticing is enough for now." },
          ],
        },
      ],
    },

    {
      id: "m2",
      n: 2,
      title: "Recognizing Your Patterns",
      subtitle: "Self-awareness",
      tagline: "You can't change what you can't see. This module helps you see clearly.",
      goal: "Users start connecting triggers to responses.",
      lessons: [
        {
          id: "l2-1",
          kind: "lesson",
          title: "Common Anxiety Triggers and How to Spot Yours",
          readTime: "4 min read",
          body: [
            { t: "p", text: "A trigger is anything — a situation, a person, a thought, a memory, even a smell — that activates your anxiety response. Triggers aren't the cause of anxiety itself, but they are the doorway through which it enters." },
            { t: "p", text: "Most people spend years feeling anxious without ever clearly identifying what sets it off. They just know they feel bad, often, and can't explain why. Learning to spot your triggers is one of the most empowering things you can do because it turns anxiety from something that happens to you into something you can anticipate and prepare for." },
            { t: "h", text: "Situational triggers" },
            { t: "list", items: [
              "Public speaking or being the center of attention",
              "Conflict or confrontation with others",
              "New environments or unfamiliar social situations",
              "Medical appointments or health concerns",
              "Financial pressure or uncertainty",
            ] },
            { t: "h", text: "Relational triggers" },
            { t: "list", items: [
              "Feeling rejected, excluded, or criticized",
              "Relationships that feel unstable or unpredictable",
              "Difficulty saying no or setting boundaries",
              "Feeling misunderstood or unseen",
            ] },
            { t: "h", text: "Internal triggers" },
            { t: "list", items: [
              "Physical sensations like a racing heart or dizziness — which can themselves trigger anxiety",
              "Memories of past difficult experiences",
              "Uncertainty about the future",
              "Feeling out of control",
            ] },
            { t: "h", text: "Environmental triggers" },
            { t: "list", items: [
              "Loud or chaotic environments",
              "Too much screen time or news consumption",
              "Poor sleep or skipped meals",
              "Caffeine or alcohol",
            ] },
            { t: "p", text: "Here's something important: the same situation can be triggering for one person and completely neutral for another. Triggers are personal. They're shaped by your history, your nervous system, and your experiences." },
            { t: "h", text: "How to start spotting yours:" },
            { t: "p", text: "Begin paying attention to the moments just before anxiety spikes. Ask yourself: Where was I? Who was I with? What was I thinking about? What had just happened?" },
            { t: "p", text: "You don't need to analyze it deeply right away. Just notice. Patterns will start to emerge over time — and when they do, you'll have real information to work with." },
            { t: "take", text: "Triggers are personal and learnable. Identifying yours turns anxiety from something mysterious into something you can work with." },
          ],
        },
        {
          id: "l2-2",
          kind: "lesson",
          title: "Physical vs. Emotional vs. Behavioral Symptoms",
          readTime: "5 min read",
          body: [
            { t: "p", text: "Anxiety doesn't announce itself the same way for everyone. For some people it screams through the body — tight chest, racing heart, difficulty breathing. For others it's quieter but persistent — a low hum of dread, difficulty concentrating, or a constant feeling of being on edge." },
            { t: "p", text: "Understanding how anxiety shows up for you specifically helps you catch it earlier and respond more effectively. Anxiety expresses itself across three dimensions:" },
            { t: "h", text: "Physical symptoms" },
            { t: "list", items: [
              "Racing or pounding heartbeat",
              "Shortness of breath or feeling like you can't get a full breath",
              "Chest tightness or pressure",
              "Muscle tension — particularly neck, shoulders, and jaw",
              "Headaches or migraines",
              "Upset stomach, nausea, or digestive issues",
              "Sweating, trembling, or feeling shaky",
              "Fatigue — anxiety is exhausting even when you haven't done anything physically demanding",
              "Difficulty sleeping or waking in the night with a racing mind",
            ] },
            { t: "h", text: "Emotional symptoms" },
            { t: "list", items: [
              "Persistent worry that feels difficult to turn off",
              "A sense of dread or feeling that something bad is about to happen",
              "Feeling overwhelmed or unable to cope",
              "Irritability or a short fuse — anxiety often presents as frustration",
              "Feeling detached from yourself or your surroundings",
              "A general sense of unease you can't quite explain",
              "Difficulty feeling joy or relaxation even when things are going well",
            ] },
            { t: "h", text: "Behavioral symptoms" },
            { t: "list", items: [
              "Avoiding situations, places, or conversations that feel threatening",
              "Procrastinating on tasks that feel overwhelming",
              "Overworking or staying constantly busy to avoid sitting with discomfort",
              "Seeking frequent reassurance from others",
              "Withdrawing from social situations",
              "Checking behaviors — repeatedly checking locks, messages, health symptoms",
              "Difficulty making decisions for fear of choosing wrong",
            ] },
            { t: "p", text: "Many people only recognize their anxiety through one channel — usually the most obvious one. Someone might notice their tight shoulders but miss the avoidance behavior. Someone else might recognize the worry but dismiss the exhaustion as just being \"tired.\"" },
            { t: "p", text: "Anxiety is a whole-system experience. The more dimensions you can recognize, the earlier you catch it — and the more tools you have to address it." },
            { t: "take", text: "Anxiety shows up physically, emotionally, and behaviorally. Knowing all three channels helps you recognize it sooner and respond smarter." },
          ],
        },
        {
          id: "l2-3",
          kind: "lesson",
          title: "Anxiety Styles: Avoidance, Overthinking, and People-Pleasing",
          readTime: "5 min read",
          body: [
            { t: "p", text: "Beyond symptoms, most people develop a dominant style of anxiety — a characteristic way their anxiety expresses and protects itself. These styles develop early in life, often as smart adaptations to difficult environments. But over time they can become the very thing keeping anxiety alive." },
            { t: "p", text: "There are three common anxiety styles. You may recognize yourself in one primarily, or in elements of all three." },
            { t: "h", text: "The Avoider" },
            { t: "p", text: "Avoiders manage anxiety by steering clear of anything that might trigger it. They cancel plans when social anxiety spikes. They delay difficult conversations indefinitely. They stay in jobs, relationships, or situations that feel \"safe\" even when they're unfulfilling — because the alternative feels unbearably uncertain." },
            { t: "p", text: "Avoidance works brilliantly in the short term. The anxiety drops almost immediately when you decide not to do the scary thing. But the relief is temporary, and the cost accumulates. Life gradually shrinks. Confidence erodes. And the avoided thing becomes more frightening with every year it goes unaddressed." },
            { t: "quote", label: "Signs you might be an Avoider", text: "A growing list of things you \"can't\" do, places you \"don't go,\" or conversations you've been meaning to have for months or years." },
            { t: "h", text: "The Overthinker" },
            { t: "p", text: "Overthinkers manage anxiety through mental control. If they can just think through every possible scenario — every outcome, every risk, every contingency — they'll feel prepared. Safe. In control." },
            { t: "p", text: "The problem is that thinking about an uncertain future doesn't make it more certain. It just generates more thoughts to think about. Overthinkers often mistake worry for productive problem-solving. They feel like they're doing something about the anxiety when they're actually feeding it." },
            { t: "p", text: "Overthinking also tends to live in two time zones: the past (\"Why did I say that? What did they think of me?\") and the future (\"What if this goes wrong? What if I can't handle it?\"). Neither is where real life happens." },
            { t: "quote", label: "Signs you might be an Overthinker", text: "Difficulty switching off at night, replaying conversations after they've ended, needing to \"figure everything out\" before feeling okay." },
            { t: "h", text: "The People-Pleaser" },
            { t: "p", text: "People-pleasers manage anxiety through connection and approval. If everyone around them is happy — if no one is upset, disappointed, or critical — they feel safe. So they say yes when they mean no. They absorb other people's emotions. They work twice as hard to avoid conflict or disapproval." },
            { t: "p", text: "This style often looks like kindness or generosity from the outside. Internally it's exhausting. People-pleasers are often deeply attuned to others' moods, constantly scanning for signs of disapproval. Their sense of safety depends on things they can't actually control — how other people feel." },
            { t: "quote", label: "Signs you might be a People-Pleaser", text: "Difficulty saying no, feeling responsible for other people's emotions, resentment that builds quietly because your own needs keep getting deprioritized." },
            { t: "p", text: "An important note: these styles are not personality flaws. They were often the wisest response available to you at a certain point in your life. Recognizing yours isn't about blame — it's about understanding the pattern well enough to start making different choices. In the modules ahead, we'll build tools that directly address each of these styles." },
            { t: "take", text: "Most people have a dominant anxiety style — Avoider, Overthinker, or People-Pleaser. Recognizing yours is a major step toward changing it." },
          ],
        },
        {
          id: "l2-e",
          kind: "exercise",
          title: "Trigger Tracking Worksheet",
          readTime: "Exercise",
          body: [
            { t: "p", text: "Use this over the next few days. The goal isn't to eliminate anxiety — it's to understand it better. Each time you notice anxiety rising, pause and note:" },
            { t: "fields", intro: "", rows: [
              { label: "When did it happen?", hint: "Date / time of day" },
              { label: "Where were you?", hint: "Location or situation" },
              { label: "What triggered it?", hint: "Event, thought, or person" },
              { label: "Physical symptoms", hint: "What did you feel in your body?" },
              { label: "Emotional symptoms", hint: "What were you feeling emotionally?" },
              { label: "What did you do?", hint: "How did you respond behaviorally?" },
              { label: "Anxiety style", hint: "Avoider / Overthinker / People-Pleaser?" },
            ] },
            { t: "p", text: "Even two or three entries will start revealing patterns you've never noticed before." },
          ],
        },
      ],
    },

    {
      id: "m3",
      n: 3,
      title: "In-the-Moment Tools",
      subtitle: "Quick relief skills",
      tagline: "When anxiety peaks, you need tools that work fast. These do.",
      goal: "Practical techniques they can use immediately.",
      lessons: [
        {
          id: "l3-1",
          kind: "lesson",
          title: "Breathing Techniques: Box Breathing & 4-7-8",
          readTime: "4 min read",
          body: [
            { t: "p", text: "When anxiety spikes, your breathing is one of the fastest pathways back to calm — and it's always available to you. No equipment. No privacy required. No one even needs to know you're doing it." },
            { t: "h", text: "Here's why it works:" },
            { t: "p", text: "Your breathing is one of the few bodily functions that operates both automatically and under your conscious control. When you deliberately slow and deepen your breath, you activate your parasympathetic nervous system — the part responsible for rest and recovery. This directly counteracts the fight-or-flight response anxiety triggers." },
            { t: "p", text: "Within just a few breaths, your heart rate begins to slow, your muscles start to release tension, and your mind gets a signal that the threat has passed." },
            { t: "h", text: "Technique 1: Box Breathing" },
            { t: "p", text: "Box breathing is used by everyone from Navy SEALs to surgeons to calm the nervous system under pressure. It's simple, structured, and works quickly. Inhale slowly through your nose for 4 counts, hold for 4 counts, exhale slowly through your mouth for 4 counts, hold again for 4 counts. Repeat this cycle 4–6 times." },
            { t: "p", text: "The \"box\" refers to the four equal sides of the breath — in, hold, out, hold. The structure gives your mind something to focus on, which interrupts the spiral of anxious thoughts while calming your body. Best used for moments before a stressful event — a presentation, a difficult conversation, a medical appointment." },
            { t: "interactive", widget: "breath-box" },
            { t: "h", text: "Technique 2: 4-7-8 Breathing" },
            { t: "p", text: "This technique works slightly differently. The extended exhale is the key — a longer out-breath activates the vagus nerve, which plays a central role in calming your entire nervous system. Inhale quietly through your nose for 4 counts, hold for 7 counts, exhale completely through your mouth for 8 counts with a gentle whoosh. Repeat 3–4 cycles to start. Don't do more than 4 cycles at first as it can cause lightheadedness." },
            { t: "p", text: "Best used for anxiety that has already escalated, difficulty sleeping due to a racing mind, or moments when you feel overwhelmed and need to reset quickly." },
            { t: "interactive", widget: "breath-478" },
            { t: "p", text: "A practical note: neither technique will feel natural the first time. That's normal. The more you practice them outside of anxious moments, the more effectively they'll work inside them. Think of it like a fire drill — you practice before the emergency so the response becomes automatic when you need it." },
            { t: "take", text: "Controlled breathing directly calms your nervous system. Box breathing and 4-7-8 are two reliable techniques you can use anywhere, anytime." },
          ],
        },
        {
          id: "l3-2",
          kind: "lesson",
          title: "Grounding Techniques: The 5-4-3-2-1 Method",
          readTime: "4 min read",
          body: [
            { t: "p", text: "Anxiety pulls you out of the present moment. It drags your mind into the future — the what-ifs, the worst cases, the endless possibilities of things going wrong. Grounding techniques do the opposite. They anchor you firmly back in the here and now, using your five senses as the rope." },
            { t: "p", text: "The most widely used and effective grounding technique is the 5-4-3-2-1 method. When anxiety rises, pause wherever you are and work through each sense deliberately. Use the interactive tool below to walk through it now." },
            { t: "interactive", widget: "grounding" },
            { t: "h", text: "Why it works" },
            { t: "p", text: "Your five senses are anchored in the present moment. They cannot perceive the future — only what is happening right now. By deliberately engaging them, you shift your brain's attention from the imagined threat driving your anxiety to the actual, immediate reality around you." },
            { t: "p", text: "Most people find that by the time they finish all five steps, the intensity of the anxiety has noticeably reduced — not gone, but manageable enough to think clearly." },
            { t: "h", text: "A variation for more intense moments" },
            { t: "p", text: "If anxiety is very high and the full 5-4-3-2-1 feels like too much, start with just one sense. Pick up an object — a pen, your phone, a cup — and describe it in as much physical detail as possible. Texture, weight, temperature, color, shape. This micro-grounding exercise can break the anxiety spiral in under a minute." },
            { t: "take", text: "The 5-4-3-2-1 method uses your senses to bring you back to the present moment, interrupting the anxious mind's grip on imagined future threats." },
          ],
        },
        {
          id: "l3-3",
          kind: "lesson",
          title: "Body Scan: Releasing Physical Tension",
          readTime: "4 min read",
          body: [
            { t: "p", text: "Anxiety doesn't just live in your mind — it stores itself in your body. Tight shoulders you've been carrying for days. A jaw clenched so long you've stopped noticing. A chest that never quite fully opens. Most people carry chronic physical tension without realizing it because it's become their baseline — their normal." },
            { t: "p", text: "A body scan is a simple practice that systematically brings your awareness through your body from head to toe, noticing where tension is being held and consciously releasing it. It's not complicated. It doesn't require any special skill. But done regularly, it can dramatically reduce the physical burden anxiety places on your body." },
            { t: "p", text: "Find a comfortable position — seated or lying down. Close your eyes if you're comfortable. Take two or three slow, deep breaths to begin. Then work down through your body, releasing each area as you go:" },
            { t: "interactive", widget: "bodyscan" },
            { t: "p", text: "After the scan, take a few moments before opening your eyes. Notice how your body feels now compared to when you started. Often there's a tangible difference — a softness or heaviness that wasn't there before. You don't need to achieve perfect relaxation. The practice is in the noticing — becoming aware of where your body holds anxiety so you can start to release it rather than carry it indefinitely." },
            { t: "p", text: "How often: Even 5 minutes once a day builds significant awareness over time. It's also a powerful tool right before sleep when physical tension makes it hard to wind down." },
            { t: "take", text: "Tension stored in the body is a physical form of anxiety. A body scan helps you locate and release it — turning awareness itself into relief." },
          ],
        },
        {
          id: "l3-a",
          kind: "audio",
          title: "Audio Exercise — The 5-Minute Anxiety Reset",
          readTime: "🎧 5 min guided",
          body: [
            { t: "p", text: "This is a guided session combining all three techniques from this module into one seamless experience. It can be used anytime anxiety rises or as a daily reset practice. Press play below — your device will read the guided script aloud. Find a comfortable position, and let yourself arrive." },
            { t: "interactive", widget: "audio-reset" },
            { t: "p", text: "Whatever was sitting on your chest when you started — it may still be there. But you are not at the mercy of it. You have tools. And you just used them." },
          ],
        },
      ],
    },

    {
      id: "m4",
      n: 4,
      title: "Changing the Thinking",
      subtitle: "Cognitive tools",
      tagline: "Your thoughts feel like facts. Often, they're just first drafts.",
      goal: "Addressing the mental patterns that fuel anxiety.",
      lessons: [
        {
          id: "l4-1",
          kind: "lesson",
          title: "What Is an Anxious Thought vs. a Realistic Thought?",
          readTime: "4 min read",
          body: [
            { t: "p", text: "Here's something most people never question: just because a thought feels true doesn't mean it is true." },
            { t: "p", text: "Anxious thoughts have a particular quality to them. They arrive fast, feel urgent, and often present themselves as absolute fact rather than one possible interpretation among many. \"I'm going to fail this.\" \"They're upset with me.\" \"Something bad is going to happen.\" These thoughts don't feel like guesses — they feel like certainties." },
            { t: "p", text: "But anxious thoughts and realistic thoughts are not the same thing, even though they can feel identical in the moment. Here's how they tend to differ:" },
            { t: "h", text: "Anxious thoughts usually:" },
            { t: "list", items: [
              "Focus on worst-case scenarios",
              "Treat possibilities as certainties (\"this will happen\" rather than \"this could happen\")",
              "Are absolute — using words like always, never, everyone, no one",
              "Skip straight to the most extreme conclusion",
              "Feel urgent and demand immediate emotional reaction",
            ] },
            { t: "h", text: "Realistic thoughts usually:" },
            { t: "list", items: [
              "Consider a range of possible outcomes, not just the worst one",
              "Account for evidence — what's actually happened before in similar situations",
              "Allow for uncertainty without needing to resolve it immediately",
              "Leave room for nuance — \"this is hard\" rather than \"this is impossible\"",
            ] },
            { t: "quote", label: "Example — a friend hasn't replied for hours", text: "Anxious thought: \"They're ignoring me. I must have said something wrong.\" Realistic thought: \"They haven't replied yet. People get busy. There are lots of reasons — most of which have nothing to do with me.\"" },
            { t: "p", text: "Notice that the realistic thought isn't blind positivity. It's not \"everything is definitely fine!\" It's simply open — it doesn't rush to the worst conclusion as if it were already confirmed." },
            { t: "p", text: "This isn't about telling yourself anxious thoughts are \"wrong\" or that you should just \"think positive.\" Anxious thoughts often contain a kernel of something real — a genuine concern, a real possibility. The goal isn't to dismiss them. It's to notice when a thought has jumped from possible to certain without any actual evidence — and to gently widen the lens back out." },
            { t: "take", text: "Anxious thoughts often present themselves as facts when they're really just one possibility among many. Learning to spot the difference is the foundation of cognitive reframing." },
          ],
        },
        {
          id: "l4-2",
          kind: "lesson",
          title: "Common Thinking Traps",
          readTime: "5 min read",
          body: [
            { t: "p", text: "Anxious minds tend to fall into recognizable patterns — mental shortcuts that feel automatic but distort how we see situations. Psychologists call these thinking traps (or cognitive distortions). They're called \"traps\" because they're easy to fall into and hard to notice from the inside — they just feel like thinking." },
            { t: "p", text: "The good news: once you can name a thinking trap, it starts to lose some of its grip. Here are the most common ones." },
            { t: "h", text: "1. Catastrophizing" },
            { t: "p", text: "Jumping to the worst possible outcome — and treating it as the most likely outcome. Example: \"My boss wants to talk to me tomorrow. I'm probably getting fired.\" In reality, there are dozens of mundane reasons a boss might want to talk. Catastrophizing skips past all of those and lands on the most extreme, least likely option." },
            { t: "h", text: "2. All-or-Nothing Thinking (Black-and-White Thinking)" },
            { t: "p", text: "Seeing things in absolute categories with no middle ground — success or failure, perfect or worthless, safe or dangerous. Example: \"I made one mistake in the presentation, so the whole thing was a disaster.\" This trap erases all the nuance of real life, where most things exist on a spectrum." },
            { t: "h", text: "3. Mind Reading" },
            { t: "p", text: "Assuming you know what someone else is thinking — usually that it's negative — without any actual evidence. Example: \"She looked at me weird in the meeting. She probably thinks I'm incompetent.\" Mind reading often says more about our own insecurities than about what the other person is actually thinking." },
            { t: "h", text: "4. Fortune Telling" },
            { t: "p", text: "Predicting the future with certainty — almost always negatively. Example: \"I know this is going to go badly.\" This trap treats an unknown future as if it's already been decided, often leading to avoidance of things that might have actually gone fine." },
            { t: "h", text: "5. Should Statements" },
            { t: "p", text: "Holding yourself (or others) to rigid, often unrealistic standards using words like should, must, or have to. Example: \"I should be able to handle this without feeling anxious at all.\" These statements create pressure and often guilt or shame when they're not met." },
            { t: "h", text: "6. Emotional Reasoning" },
            { t: "p", text: "Believing that because you feel something strongly, it must be true. Example: \"I feel like a failure, so I must be one.\" Feelings are real and valid — but they aren't always accurate reflections of reality." },
            { t: "h", text: "7. Filtering (Mental Filter)" },
            { t: "p", text: "Focusing exclusively on the negative details of a situation while filtering out anything positive. Example: Receiving feedback that's 90% positive and one suggestion for improvement — and only being able to think about the suggestion." },
            { t: "p", text: "You don't need to memorize these terms. What matters is starting to notice: \"Oh — that's catastrophizing.\" \"That sounds like mind reading.\" Simply naming the pattern creates a small but important gap between you and the thought." },
            { t: "take", text: "Anxious minds fall into predictable thinking traps. Naming them is the first step to loosening their grip." },
          ],
        },
        {
          id: "l4-3",
          kind: "lesson",
          title: "How to Challenge and Reframe Anxious Thoughts",
          readTime: "5 min read",
          body: [
            { t: "p", text: "Once you can recognize an anxious thought and the thinking trap behind it, the next step is learning how to respond to it — not by forcing yourself to \"think positive,\" but by examining the thought more honestly and completely. This process is called cognitive reframing." },
            { t: "h", text: "Step 1: Catch the thought" },
            { t: "p", text: "Simply notice that an anxious thought has occurred — and, ideally, write it down. Putting a thought into words moves it from the swirling, abstract space of your mind into something concrete you can actually look at. Example thought: \"I sent that email and now my coworker is definitely annoyed with me.\"" },
            { t: "h", text: "Step 2: Identify the thinking trap" },
            { t: "p", text: "Ask yourself which pattern this resembles. In this example, it might be a mix of mind reading (assuming you know what they're thinking) and fortune telling (assuming a negative outcome is certain). Simply identifying the trap creates distance. The thought shifts from \"this is true\" to \"this is a pattern I recognize.\"" },
            { t: "h", text: "Step 3: Examine the evidence" },
            { t: "list", items: [
              "What evidence do I actually have that this is true?",
              "Is there another explanation that fits the situation just as well — or better?",
              "What would I say to a friend who had this exact thought?",
              "Have I had this thought before in a similar situation — and what actually happened?",
              "If this worst-case scenario did happen, how would I cope? Would it really be as unbearable as it feels right now?",
            ] },
            { t: "p", text: "These questions aren't about forcing yourself into fake optimism. They're about widening the lens — looking at the full picture rather than the one narrow frame anxiety is zoomed in on." },
            { t: "h", text: "Step 4: Build a balanced thought" },
            { t: "quote", label: "From anxious to balanced", text: "Anxious: \"My coworker is definitely annoyed with me.\" Balanced: \"I don't actually know how they felt about the email. They might not have even read it that closely. Even if they were a little annoyed, that's not the end of the world — and it doesn't mean anything about me as a person or colleague.\"" },
            { t: "p", text: "This process can feel slow and effortful at first — almost mechanical. That's normal. Over time, with repetition, this kind of thinking starts to happen more naturally. You're not trying to eliminate anxious thoughts entirely. You're building a habit of checking in with them rather than automatically believing everything they say." },
            { t: "take", text: "Reframing isn't about thinking positive — it's about thinking completely. Catch the thought, name the trap, examine the evidence, and build a more balanced perspective." },
          ],
        },
        {
          id: "l4-e",
          kind: "exercise",
          title: "Thought Record",
          readTime: "Exercise",
          body: [
            { t: "p", text: "Use this whenever you notice a strong anxious thought. It only takes a few minutes, and it gets easier with practice." },
            { t: "fields", intro: "", rows: [
              { label: "Situation", hint: "What was happening when the thought occurred?" },
              { label: "Anxious thought", hint: "What exactly did you think? Write it as a sentence." },
              { label: "Emotion + intensity", hint: "What did you feel, and how strong was it (1–10)?" },
              { label: "Thinking trap", hint: "Catastrophizing, mind reading, all-or-nothing, etc." },
              { label: "Evidence for", hint: "What facts actually support this thought?" },
              { label: "Evidence against", hint: "What facts don't fit, or point another direction?" },
              { label: "Balanced thought", hint: "Rewrite the thought to be more complete and realistic" },
              { label: "New emotion + intensity", hint: "How do you feel now, and how strong is it (1–10)?" },
            ] },
            { t: "p", text: "The goal isn't to get the intensity to zero. Even a small shift — from an 8 to a 6 — is meaningful progress." },
          ],
        },
      ],
    },

    {
      id: "m5",
      n: 5,
      title: "Building Long-Term Resilience",
      subtitle: "Lifestyle & habits",
      tagline: "Managing anxiety in the moment is essential. Making it less likely to spike in the first place is the goal.",
      goal: "Moving from managing anxiety to building resistance to it.",
      lessons: [
        {
          id: "l5-1",
          kind: "lesson",
          title: "The Role of Sleep, Movement, and Nutrition in Anxiety",
          readTime: "5 min read",
          body: [
            { t: "p", text: "Anxiety is not purely a psychological experience. It is deeply biological — shaped by the state of your body just as much as the state of your mind. Three of the most powerful influences on your anxiety levels are also three of the most underestimated: how you sleep, how you move, and how you eat." },
            { t: "p", text: "Most people try to manage anxiety entirely in their head — through thinking differently, through willpower, through just pushing through. But if your body is chronically sleep-deprived, physically inactive, or running on poor nutrition, you are fighting anxiety with one hand tied behind your back." },
            { t: "h", text: "Sleep" },
            { t: "p", text: "Sleep and anxiety have a complicated, two-directional relationship. Anxiety makes it harder to sleep — racing thoughts, physical tension, and a nervous system that won't fully switch off all interfere with rest. But poor sleep also directly worsens anxiety, creating a cycle that can feel almost impossible to break." },
            { t: "p", text: "When you're sleep-deprived, your amygdala — the brain's alarm center — becomes significantly more reactive. Even one night of poor sleep can increase emotional reactivity by up to 60%. At the same time, the prefrontal cortex — responsible for rational thinking and emotional regulation — becomes less active. So your ability to apply the reframing skills from Module 4 is literally reduced when you haven't slept well." },
            { t: "list", items: [
              "Prioritizing sleep is not a luxury — it is one of the most direct interventions for anxiety available",
              "Consistent sleep and wake times (even on weekends) stabilize your body's internal clock and reduce anxiety baseline",
              "A wind-down routine signals your nervous system that it's safe to rest",
            ] },
            { t: "h", text: "Movement" },
            { t: "p", text: "Exercise is one of the most effective anxiety interventions that exists — comparable in some studies to medication for mild to moderate anxiety. Physical activity burns off the excess adrenaline and cortisol that anxiety produces. It triggers the release of endorphins, serotonin, and BDNF — a protein that supports the growth of new neural connections and helps your brain become more resilient over time." },
            { t: "list", items: [
              "Any movement is better than none",
              "Even a 20–30 minute walk that raises your heart rate slightly produces measurable anxiety reduction",
              "Outdoor movement adds natural light and environment, both of which reduce cortisol",
              "Movement works best as a preventive practice rather than only reaching for it when anxiety peaks",
            ] },
            { t: "h", text: "Nutrition" },
            { t: "p", text: "What you eat directly affects your brain chemistry — and therefore your anxiety levels. Certain nutritional patterns consistently either support or undermine your nervous system's stability." },
            { t: "list", items: [
              "Caffeine — stimulates the nervous system and can mimic or amplify anxiety, especially late in the day",
              "Alcohol — temporarily reduces anxiety but disrupts sleep and increases rebound anxiety the next day",
              "High sugar intake — blood sugar spikes and crashes create sensations that can mimic anxiety",
              "Skipping meals — low blood sugar activates a stress response in the body",
            ] },
            { t: "list", items: [
              "Regular, balanced meals that stabilize blood sugar throughout the day",
              "Omega-3 rich foods (oily fish, walnuts, flaxseed) support brain health and reduced anxiety",
              "Magnesium (leafy greens, nuts, seeds, dark chocolate) helps regulate the nervous system and is depleted by chronic stress",
              "Staying well hydrated — even mild dehydration increases cortisol",
            ] },
            { t: "take", text: "Sleep, movement, and nutrition are not separate from your mental health — they are the biological foundation it rests on. Improving any one of them directly reduces your anxiety baseline." },
          ],
        },
        {
          id: "l5-2",
          kind: "lesson",
          title: "How to Build a Daily Stress Management Routine",
          readTime: "5 min read",
          body: [
            { t: "p", text: "The tools in this course only work if they get used — and they only get used consistently if they're built into a routine. A stress management routine isn't about adding more to your plate. It's about intentionally placing small, protective practices into the architecture of your day so they happen naturally rather than only when you're already overwhelmed." },
            { t: "p", text: "Think of it like this: you don't wait until your teeth hurt to brush them. Daily stress management works the same way — regular maintenance prevents the buildup that leads to crisis. The two most important anchors are morning and evening, because routines attached to waking up and going to sleep are far more likely to stick." },
            { t: "h", text: "A morning routine for anxiety" },
            { t: "list", items: [
              "Don't reach for your phone immediately — even 10 minutes without notifications lets your nervous system come online gently",
              "A few minutes of intentional breathing — 2–3 minutes of box breathing after waking starts the day from a calmer baseline",
              "Light exposure — opening curtains or stepping outside regulates cortisol rhythm and improves mood and alertness",
              "A grounding moment — take 60 seconds to notice three things you can see, hear, or feel before the day pulls you in",
            ] },
            { t: "h", text: "An evening routine for anxiety" },
            { t: "list", items: [
              "A consistent wind-down window — the 45–60 minutes before sleep ideally involves no screens, no work, and no high-stakes conversations",
              "A brief reflection practice — note three things that went well today (however small) to counter anxiety's negativity bias",
              "Progressive muscle relaxation or body scan — releasing physical tension before sleep improves sleep onset and quality",
              "Writing worries down — offloading tomorrow's concerns onto paper reduces nighttime rumination",
            ] },
            { t: "p", text: "Start small. Don't try to implement everything at once — that's the fastest path to abandoning the whole thing. Choose one practice from the morning list and one from the evening list. Do those consistently for two weeks before adding anything else. The goal isn't a perfect routine. It's a consistent one." },
            { t: "take", text: "A daily stress management routine doesn't need to be long or complex. Two or three intentional practices in the morning and evening — done consistently — create a significantly more resilient nervous system over time." },
          ],
        },
        {
          id: "l5-3",
          kind: "lesson",
          title: "Setting Boundaries to Protect Your Mental Energy",
          readTime: "5 min read",
          body: [
            { t: "p", text: "Every day you have a finite amount of mental and emotional energy. Anxiety is one of the heaviest consumers of that energy — it runs in the background constantly, taxing your system even when you're not actively aware of it." },
            { t: "p", text: "Boundaries are one of the most underrated anxiety management tools because they address something the other tools don't: the external demands and dynamics that drain your energy and keep your nervous system in a state of chronic activation. A boundary isn't a wall or a rejection. It's a decision about what you will and won't give your energy to — and communicating that decision clearly." },
            { t: "p", text: "This is especially relevant if you recognized yourself as a People-Pleaser in Module 2. Boundaries feel threatening to an anxious mind because they involve disappointing someone, uncertainty about how they'll react, and potential conflict. So the path of least resistance feels like saying yes — staying available, absorbing more than your fair share. The cost over time is significant: chronic overextension depletes the exact resources you need to manage anxiety." },
            { t: "h", text: "Time boundaries" },
            { t: "list", items: [
              "Are you saying yes to commitments that leave you no time to rest or recover?",
              "Do you check work messages outside work hours in a way that keeps your nervous system activated?",
              "Are you giving time to things or people that consistently drain rather than restore you?",
            ] },
            { t: "h", text: "Emotional boundaries" },
            { t: "list", items: [
              "Are you taking on responsibility for other people's feelings — managing their moods, absorbing their stress?",
              "Are there relationships that leave you consistently feeling worse rather than better?",
              "Do you find yourself doing emotional labor that no one asked you to do and that isn't yours to carry?",
            ] },
            { t: "h", text: "Information boundaries" },
            { t: "list", items: [
              "How much news are you consuming — does it inform you or keep your threat-detection system permanently activated?",
              "Is social media leaving you feeling connected and inspired, or compared and inadequate?",
              "Who in your life consistently generates stress, and how much access do you give them?",
            ] },
            { t: "h", text: "How to actually set a boundary" },
            { t: "ol", items: [
              "Name what you need clearly — to yourself first, then to the other person. Vague limits are easy to override.",
              "State it simply and directly — you don't owe an extensive explanation. \"I can't take that on right now\" is complete.",
              "Expect discomfort — the other person may push back and your nervous system will spike. This is normal. It doesn't mean the boundary was wrong.",
              "Hold it — a boundary stated once and then abandoned teaches people (and your own nervous system) that it wasn't real.",
            ] },
            { t: "quote", label: "A reframe worth keeping", text: "Every time you say no to something that drains you, you are saying yes to something that restores you. Boundaries aren't about shutting people out — they're about protecting the energy you need to show up fully for what actually matters to you." },
            { t: "take", text: "Boundaries protect the mental and emotional energy that anxiety continuously depletes. Learning to set them — even imperfectly — is one of the most practical long-term anxiety management skills available." },
          ],
        },
        {
          id: "l5-r",
          kind: "reflection",
          title: "My Personal Anxiety Management Plan",
          readTime: "Reflection",
          body: [
            { t: "p", text: "This reflection brings everything from this module together into a simple, personal plan you can actually use. There are no right answers — only honest ones." },
            { t: "fields", intro: "Sleep", rows: [
              { label: "What does my current sleep look like honestly?", hint: "Quality, consistency, duration" },
              { label: "One thing I could change this week to protect my sleep", hint: "" },
            ] },
            { t: "fields", intro: "Movement", rows: [
              { label: "How much am I currently moving each day?", hint: "" },
              { label: "One realistic way I could add more movement this week", hint: "" },
            ] },
            { t: "fields", intro: "Nutrition", rows: [
              { label: "Any patterns in my eating that affect my anxiety?", hint: "Caffeine, skipped meals, alcohol, blood sugar" },
              { label: "One small nutritional change I'm willing to try", hint: "" },
            ] },
            { t: "fields", intro: "Daily Routine", rows: [
              { label: "The morning practice I want to start with", hint: "" },
              { label: "The evening practice I want to start with", hint: "" },
              { label: "I will try these consistently for…", hint: "number of weeks before adding more" },
            ] },
            { t: "fields", intro: "Boundaries", rows: [
              { label: "One area of my life where I'm currently overextended", hint: "" },
              { label: "One boundary I've been avoiding setting", hint: "" },
              { label: "What I will say, and to whom", hint: "" },
            ] },
            { t: "p", text: "You don't need to do all of this at once. Pick the one change that feels most important right now and begin there. Progress compounds — small consistent shifts create significant change over time." },
          ],
        },
      ],
    },

    {
      id: "m6",
      n: 6,
      title: "When to Seek More Help",
      subtitle: "Safety & guidance",
      tagline: "This course is a powerful starting point. For some people, it's also a doorway to something more.",
      goal: "Normalize professional support without fear.",
      lessons: [
        {
          id: "l6-1",
          kind: "lesson",
          title: "Signs Your Anxiety Needs Professional Attention",
          readTime: "4 min read",
          body: [
            { t: "p", text: "Everything in this course so far has been built around self-help tools — practices you can apply on your own. For many people, these tools make a significant and lasting difference. But self-help has limits. One of the most important things this course can do is help you recognize when those limits have been reached." },
            { t: "p", text: "Seeking professional help is not a sign that you've failed. It's a sign that you're taking your mental health as seriously as you would a physical health concern — and getting the right level of support for what you're actually dealing with." },
            { t: "h", text: "Signs it's time to speak to a professional" },
            { t: "list", items: [
              "It's significantly affecting your daily functioning — your ability to work, maintain relationships, care for yourself, or complete basic tasks",
              "You're avoiding more and more of your life — your world is getting smaller to accommodate your anxiety",
              "Physical symptoms are persistent and unexplained — chronic headaches, digestive issues, fatigue, chest tightness that tests can't explain",
              "The tools aren't working — you've genuinely engaged with self-help consistently and found minimal relief",
              "You're using substances to cope — alcohol, cannabis, medication, or others to numb anxiety or get through situations",
              "You're experiencing panic attacks — sudden, intense episodes of overwhelming fear with physical symptoms",
              "You're having thoughts of harming yourself — please reach out for help immediately; this is a mental health emergency",
            ] },
            { t: "quote", label: "A simple question to ask yourself", text: "\"Is my anxiety costing me a life I want to be living?\" If the honest answer is yes — even partly — that's reason enough to seek support." },
            { t: "take", text: "Professional help is appropriate whenever anxiety is significantly impacting your quality of life, your functioning, or your safety. Recognizing that moment and acting on it is a form of courage, not weakness." },
          ],
        },
        {
          id: "l6-2",
          kind: "lesson",
          title: "Types of Support Available",
          readTime: "5 min read",
          body: [
            { t: "p", text: "One reason people delay seeking help is that they're not sure what \"getting help\" actually looks like. The landscape of mental health support is broader than most people realize — and different options suit different needs, circumstances, and budgets." },
            { t: "h", text: "Therapy" },
            { t: "p", text: "Working one-on-one with a trained professional to understand and address the roots of your anxiety. It's the most well-evidenced form of support and can produce lasting change. Several approaches are particularly effective:" },
            { t: "list", items: [
              "Cognitive Behavioral Therapy (CBT) — the most researched approach; helps you identify and change thought patterns and behaviors that maintain anxiety",
              "Acceptance and Commitment Therapy (ACT) — changes your relationship with anxious thoughts rather than trying to eliminate them",
              "Exposure Therapy — gradually and systematically facing feared situations in a controlled, supported way; effective for phobias, social anxiety, and OCD",
              "EMDR — uses guided eye movements alongside memory processing; effective when anxiety has roots in past trauma",
            ] },
            { t: "h", text: "Psychiatry and Medication" },
            { t: "p", text: "A psychiatrist is a medical doctor who can diagnose anxiety disorders and prescribe medication when appropriate. For moderate to severe anxiety, medication can reduce symptoms enough to make therapy and lifestyle changes more accessible. Common approaches include SSRIs and SNRIs, always prescribed and monitored by a doctor. Medication is not right for everyone and should never be self-prescribed — but for many people it represents the difference between being able to function and not." },
            { t: "h", text: "Group Therapy and Support Groups" },
            { t: "p", text: "Working with a therapist alongside others navigating similar experiences can be profoundly normalizing. Peer support groups (sometimes community-run) offer a similar sense of community and shared experience, often at no cost." },
            { t: "h", text: "Digital and Remote Support" },
            { t: "p", text: "Teletherapy has expanded access significantly, removing barriers of geography, mobility, and time. Apps, online courses, and digital tools (like this one) serve as useful complements — particularly for ongoing skill practice between sessions." },
            { t: "h", text: "Crisis Support" },
            { t: "p", text: "For moments of acute distress — when anxiety has escalated to the point of feeling unsafe or unmanageable — crisis services provide immediate, confidential support, staffed by trained professionals available at any hour. Crisis resources are listed in Lesson 6.3." },
            { t: "take", text: "Support exists across a broad spectrum — from therapy and medication to peer groups and digital tools. Finding the right fit is a process, and most people benefit from a combination of approaches rather than one solution alone." },
          ],
        },
        {
          id: "l6-3",
          kind: "lesson",
          title: "How to Talk to Someone About What You're Going Through",
          readTime: "4 min read",
          body: [
            { t: "p", text: "For many people, the hardest part of getting help isn't finding the right therapist or making the appointment. It's saying the words out loud for the first time. Anxiety has a particular way of making this step feel impossible: What if they don't understand? What if they think less of me? These are thoughts, not facts." },
            { t: "h", text: "If you're talking to a friend or family member" },
            { t: "p", text: "You don't need to explain everything at once. You just need to begin. A simple opening is enough:" },
            { t: "list", items: [
              "\"I've been struggling with anxiety lately and I wanted to tell someone I trust.\"",
              "\"Things have felt really overwhelming recently and I think I need some support.\"",
              "\"I've been going through something difficult and I'd like to talk about it if you're open to listening.\"",
            ] },
            { t: "p", text: "It's okay to name what you need: \"I don't need you to solve this — I just need you to listen for a bit.\" Not everyone will respond perfectly. If someone becomes uncomfortable, it doesn't mean you were wrong to try — it means that person may not be the right support for this particular thing." },
            { t: "h", text: "If you're talking to a doctor" },
            { t: "p", text: "Your primary care physician is often the first professional point of contact — and a very appropriate one. They can assess what you're experiencing, rule out physical contributors, refer you to mental health professionals, and discuss medication. Some clear language:" },
            { t: "list", items: [
              "\"I've been experiencing persistent anxiety that's affecting my daily life and I'd like to talk about options for support.\"",
              "\"I've been struggling with my mental health and I think I need some professional help.\"",
            ] },
            { t: "h", text: "If you're reaching out to a therapist" },
            { t: "p", text: "Most therapists offer an initial consultation to discuss what you're looking for and whether they're a good fit. It's completely appropriate to ask: \"What approach do you use for anxiety?\" \"How do you typically structure sessions?\" \"How will we know if the therapy is working?\" Finding the right therapist can take a couple of tries — the therapeutic relationship is one of the strongest predictors of outcomes, so fit matters." },
            { t: "p", text: "And if you're not ready to talk to anyone yet, that's okay too. Consider this: you are already doing something by being in this course. That is not nothing — that is the beginning of change. When you're ready, the conversation doesn't have to be perfect. It just has to happen." },
            { t: "take", text: "Asking for help is a skill, not a personality trait. It gets easier with practice — and the first conversation, however imperfect, is the most important one." },
          ],
        },
        {
          id: "l6-res",
          kind: "resources",
          title: "Resource List: Crisis Lines, Therapy Finders & Support Communities",
          readTime: "🔗 Resources",
          body: [
            { t: "p", text: "These resources are available to anyone who needs immediate support or wants to find professional help." },
            { t: "resources", groups: [
              {
                heading: "Crisis Support — Immediate Help",
                cols: ["Resource", "Contact", "Available"],
                rows: [
                  { name: "International Association for Suicide Prevention", contact: "iasp.info/resources/Crisis_Centres", href: "https://www.iasp.info/resources/Crisis_Centres/", extra: "24/7 — crisis centers by country" },
                  { name: "Crisis Text Line (US, UK, Canada, Ireland)", contact: "Text HOME to 741741", extra: "24/7" },
                  { name: "Samaritans (UK & Ireland)", contact: "116 123", href: "tel:116123", extra: "24/7" },
                  { name: "Lifeline (Australia)", contact: "13 11 14", href: "tel:131114", extra: "24/7" },
                  { name: "988 Suicide & Crisis Lifeline (US)", contact: "Call or text 988", href: "tel:988", extra: "24/7" },
                  { name: "Befrienders Kenya", contact: "+254 722 178 177", href: "tel:+254722178177", extra: "24/7 — East Africa" },
                  { name: "Kenya Red Cross", contact: "1199", href: "tel:1199", extra: "24/7 — East Africa" },
                ],
              },
              {
                heading: "Finding a Therapist",
                cols: ["Resource", "What It Does"],
                rows: [
                  { name: "Psychology Today Therapist Finder", contact: "Search by location, specialty, insurance, and budget", href: "https://www.psychologytoday.com/us/therapists" },
                  { name: "BetterHelp", contact: "Online therapy — matched with a therapist remotely", href: "https://www.betterhelp.com/" },
                  { name: "Open Path Collective", contact: "Reduced-cost therapy for those with financial constraints", href: "https://openpathcollective.org/" },
                  { name: "Your GP or Primary Care Doctor", contact: "Can refer you to local mental health services" },
                ],
              },
              {
                heading: "Support Communities",
                cols: ["Resource", "What It Offers"],
                rows: [
                  { name: "Anxiety and Depression Association of America (ADAA)", contact: "Information, peer support groups, therapist finder", href: "https://adaa.org/" },
                  { name: "Mind (UK)", contact: "Mental health information, local support groups", href: "https://www.mind.org.uk/" },
                  { name: "Beyond Blue (Australia)", contact: "Anxiety and depression support, forums, helpline", href: "https://www.beyondblue.org.au/" },
                  { name: "Reddit r/Anxiety", contact: "Peer community — not professional support, but often deeply normalizing", href: "https://www.reddit.com/r/Anxiety/" },
                ],
              },
            ] },
            { t: "quote", label: "A final note", text: "If you are in immediate danger or experiencing a mental health emergency, please contact emergency services in your country or go to your nearest emergency department. You do not need to manage a crisis alone." },
          ],
        },
      ],
    },

    {
      id: "m7",
      n: "🎓",
      title: "Course Wrap-Up",
      subtitle: "You've Come a Long Way",
      tagline: "Managing anxiety is an ongoing practice, not a destination. What matters is that you keep coming back.",
      goal: "Completion reflection + personalized next steps.",
      lessons: [
        {
          id: "l7-1",
          kind: "wrapup",
          title: "You've Come a Long Way",
          readTime: "Wrap-up",
          body: [
            { t: "p", text: "When you started this course, anxiety may have felt like something happening to you — unpredictable, overwhelming, and outside your control. You now know differently." },
            { t: "p", text: "You understand what anxiety actually is and why your body and mind respond the way they do. You can recognize your personal triggers, your physical and emotional symptoms, and the thinking patterns that have been quietly running in the background. You have real, evidence-based tools you can reach for in the moment anxiety spikes. And you have a framework for building the kind of daily resilience that makes those spikes less frequent and less intense over time." },
            { t: "p", text: "This isn't the end of the work. There will be hard days — days when everything you've learned feels out of reach. That's normal. It doesn't mean you've lost the progress you've made. What matters is that you keep coming back." },
            { t: "h", text: "Before you go, take a moment with these final questions:" },
            { t: "questions", items: [
              "What is the single most important thing you're taking away from this course?",
              "Which tool or technique do you think will be most useful for where you are right now?",
              "Is there anything from this course that makes you think professional support might be worth exploring?",
            ] },
            { t: "interactive", widget: "complete" },
          ],
        },
      ],
    },
  ],
};

// expose globally for the non-module renderer
window.COURSE = COURSE;

